### ISSUE TITLE
centos 7

### ISSUE THREAD

**Issue by dariohimo** [sinologicnet/sipcheck#14]
hola, gracias por la herramienta.
para centos 7 tengo instalado python 2.7 como puedo utilizar sipcheck v3.

gracias.

**Comment by hellc2** [comment]
If you want use `SIPCheck v3` Python 3 is required (_Python 2 is officially deprecated_)

Here you have a link where you can find how install Python 3.7 as a "alternative install" to avoid replace the default installation of Python.
https://tecadmin.net/install-python-3-7-on-centos/

Please, let me know if it works to you. :)
